labels: ["restyled"]

restylers:
  - name: black
    image: restyled/restyler-black:v19.10b0
    command:
    - black
    arguments: ["-l 79"]
    include:
    - "**/*.py"
    interpreters:
    - python
